## Gradient Descent - Boston Dataset

In [1]:
import numpy as np

In [2]:
#load data
data_train=np.genfromtxt('training_boston_x_y_train.csv',delimiter=',')
data_test=np.genfromtxt('test_boston_x_test.csv',delimiter=',')
data_train

array([[-0.40784991, -0.48772236, -1.2660231 , ...,  0.41057102,
        -1.09799011, 37.9       ],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.29116915,
        -0.52047412, 21.4       ],
       [ 0.1251786 , -0.48772236,  1.01599907, ..., -3.79579542,
         0.89107588, 12.7       ],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.33206621,
        -0.33404299, 20.8       ],
       [-0.41061997, -0.48772236, -1.15221381, ...,  0.203235  ,
        -0.74475218, 22.6       ],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.38787479,
        -1.35871335, 50.        ]])

In [3]:
data_train.shape

(379, 14)

In [4]:
col = np.ones((len(data_train),1))
data_train =np.append(data_train,col,axis =1 )#adding coloumn for the intercept
data_train.shape

(379, 15)

In [5]:
#define a function for every step of gradient
def step_gradient(points,learning_rate, m):
    m_slope= np.zeros(m.shape) 
    features = points[:,:-1].shape[1]
    M = len(points)
    for i in range(M):
        x = points[i,[0,1,2,3,4,5,6,7,8,9,10,11,12,14]] #13th is the y and 14th is intercept
        y = points[i,13]
        for j in range(features):
            m_slope[j] += (-2/M)*(y-((m*x).sum()))*x[j]
    new_m = m - learning_rate*m_slope
    return new_m

In [6]:
#define a function to find cost
def cost(points, m): #points are no.of rows and m is slope
    total_cost = 0
    M = points.shape[0]
    for i in range(M):
        x = points[i,[0,1,2,3,4,5,6,7,8,9,10,11,12,14]] # 13th coloumn is y and the 14 th coulum is intercept
        y = points[i,13]
        #y is y actual
        #y_predict is m1x1+m2x2+m3x3+....+mnxn + intercept(its added in columns ,so not needed here)
        #cost is (y actual - (sum of squres of diff betwn y actual and y predict))divide by no.of points
        total_cost += (1/M) * ((y - ((m*x).sum()))**2)
    return total_cost

In [17]:
def gradient_descent(points,learning_rate,num_iterations):
    m = np.ones(points.shape[1]-1) # -1 because we dont consider y coloumn for the slopes.
    for i in range(num_iterations):
        m = step_gradient(points, learning_rate , m)
        #uncomment the below line to print the cost for every iteration
        #print(i+1,cost(points, m))
    return m,cost(points, m)

## Try and test with various combinations of learning rates and number of iterations

### Gradient Descent for num.iterations = 300 and learning_rate = 0.01

In [8]:
gradient_descent(data_train,0.01,300)

1 562.6952524448013
2 530.7079488627438
3 502.4620720258841
4 477.2366539336533
5 454.4726054229275
6 433.73521872381315
7 414.6854063365495
8 397.0576386139467
9 380.6430177736656
10 365.27629051167094
11 350.82588081301833
12 337.1862387938227
13 324.2719656665598
14 312.013300859593
15 300.3526538806562
16 289.24193754712627
17 278.64051596829506
18 268.5136241856783
19 258.83114974577046
20 249.5666920640745
21 240.69683505560715
22 232.2005835476676
23 224.05892552298042
24 216.25449108374096
25 208.7712858071928
26 201.59448136218975
27 194.71025024265168
28 188.10563453072973
29 181.7684409466676
30 175.6871562400525
31 169.8508783558745
32 164.24925986624126
33 158.87246096971367
34 153.7111099824449
35 148.75626972270177
36 143.9994085566701
37 139.43237515461033
38 135.04737622229015
39 130.83695663837318
40 126.79398155580678
41 122.91162012313205
42 119.18333055692344
43 115.60284635451272
44 112.16416348078891
45 108.86152839729648
46 105.6894268284432
47 102.6425731802032

(array([-0.75709374,  0.29279255, -0.20838463,  0.82781999, -1.12612068,
         3.01400044,  0.09839771, -1.74649308,  1.12514589, -0.59329529,
        -1.95854275,  0.67803857, -3.88643765, 22.56685832]),
 24.347970235131875)

### Gradient Descent for num.iterations = 500 and learning_rate = 0.01

In [9]:
gradient_descent(data_train,0.01,500)

1 562.6952524448013
2 530.7079488627438
3 502.4620720258841
4 477.2366539336533
5 454.4726054229275
6 433.73521872381315
7 414.6854063365495
8 397.0576386139467
9 380.6430177736656
10 365.27629051167094
11 350.82588081301833
12 337.1862387938227
13 324.2719656665598
14 312.013300859593
15 300.3526538806562
16 289.24193754712627
17 278.64051596829506
18 268.5136241856783
19 258.83114974577046
20 249.5666920640745
21 240.69683505560715
22 232.2005835476676
23 224.05892552298042
24 216.25449108374096
25 208.7712858071928
26 201.59448136218975
27 194.71025024265168
28 188.10563453072973
29 181.7684409466676
30 175.6871562400525
31 169.8508783558745
32 164.24925986624126
33 158.87246096971367
34 153.7111099824449
35 148.75626972270177
36 143.9994085566701
37 139.43237515461033
38 135.04737622229015
39 130.83695663837318
40 126.79398155580678
41 122.91162012313205
42 119.18333055692344
43 115.60284635451272
44 112.16416348078891
45 108.86152839729648
46 105.6894268284432
47 102.6425731802032

373 24.013340781924864
374 24.009990784639115
375 24.00666641423559
376 24.00336743251855
377 24.000093604066226
378 23.996844696187495
379 23.99362047887934
380 23.99042072478548
381 23.987245209155585
382 23.984093709805766
383 23.98096600707941
384 23.97786188380926
385 23.974781125280167
386 23.971723519192327
387 23.968688855625846
388 23.965676927005475
389 23.962687528066404
390 23.959720455820566
391 23.956775509523773
392 23.953852490643346
393 23.95095120282655
394 23.9480714518694
395 23.945213045686426
396 23.94237579428072
397 23.93955950971469
398 23.936764006081347
399 23.93398909947615
400 23.931234607969476
401 23.928500351579284
402 23.92578615224471
403 23.923091833799862
404 23.920417221948185
405 23.91776214423728
406 23.915126430034285
407 23.91250991050141
408 23.90991241857233
409 23.907333788928597
410 23.904773857976657
411 23.90223246382545
412 23.89970944626386
413 23.897204646739223
414 23.894717908335714
415 23.892249075753266
416 23.88979799528695
417 23.

(array([-0.81656185,  0.43134193, -0.24882355,  0.80934619, -1.62042303,
         2.6265472 ,  0.05990451, -2.3892388 ,  1.54024331, -0.79194359,
        -2.12536639,  0.60486827, -4.16253751, 22.6555828 ]),
 23.734451887893098)

### Gradient Descent for num.iterations = 1000 and learning_rate = 0.01

In [10]:
gradient_descent(data_train,0.01,1000)

1 562.6952524448013
2 530.7079488627438
3 502.4620720258841
4 477.2366539336533
5 454.4726054229275
6 433.73521872381315
7 414.6854063365495
8 397.0576386139467
9 380.6430177736656
10 365.27629051167094
11 350.82588081301833
12 337.1862387938227
13 324.2719656665598
14 312.013300859593
15 300.3526538806562
16 289.24193754712627
17 278.64051596829506
18 268.5136241856783
19 258.83114974577046
20 249.5666920640745
21 240.69683505560715
22 232.2005835476676
23 224.05892552298042
24 216.25449108374096
25 208.7712858071928
26 201.59448136218975
27 194.71025024265168
28 188.10563453072973
29 181.7684409466676
30 175.6871562400525
31 169.8508783558745
32 164.24925986624126
33 158.87246096971367
34 153.7111099824449
35 148.75626972270177
36 143.9994085566701
37 139.43237515461033
38 135.04737622229015
39 130.83695663837318
40 126.79398155580678
41 122.91162012313205
42 119.18333055692344
43 115.60284635451272
44 112.16416348078891
45 108.86152839729648
46 105.6894268284432
47 102.6425731802032

373 24.013340781924864
374 24.009990784639115
375 24.00666641423559
376 24.00336743251855
377 24.000093604066226
378 23.996844696187495
379 23.99362047887934
380 23.99042072478548
381 23.987245209155585
382 23.984093709805766
383 23.98096600707941
384 23.97786188380926
385 23.974781125280167
386 23.971723519192327
387 23.968688855625846
388 23.965676927005475
389 23.962687528066404
390 23.959720455820566
391 23.956775509523773
392 23.953852490643346
393 23.95095120282655
394 23.9480714518694
395 23.945213045686426
396 23.94237579428072
397 23.93955950971469
398 23.936764006081347
399 23.93398909947615
400 23.931234607969476
401 23.928500351579284
402 23.92578615224471
403 23.923091833799862
404 23.920417221948185
405 23.91776214423728
406 23.915126430034285
407 23.91250991050141
408 23.90991241857233
409 23.907333788928597
410 23.904773857976657
411 23.90223246382545
412 23.89970944626386
413 23.897204646739223
414 23.894717908335714
415 23.892249075753266
416 23.88979799528695
417 23.

749 23.555891426914872
750 23.555552403103434
751 23.55521501241604
752 23.5548792450517
753 23.55454509127759
754 23.554212541428395
755 23.553881585905852
756 23.55355221517822
757 23.55322441977988
758 23.552898190310646
759 23.55257351743539
760 23.552250391883536
761 23.55192880444847
762 23.551608745987238
763 23.551290207419882
764 23.550973179729066
765 23.550657653959576
766 23.55034362121782
767 23.550031072671352
768 23.549719999548458
769 23.549410393137833
770 23.549102244787665
771 23.548795545905744
772 23.548490287958643
773 23.548186462471396
774 23.547884061027094
775 23.547583075266317
776 23.54728349688688
777 23.54698531764323
778 23.54668852934613
779 23.54639312386218
780 23.546099093113504
781 23.54580642907709
782 23.54551512378466
783 23.545225169322098
784 23.544936557829093
785 23.544649281498685
786 23.544363332576904
787 23.544078703362473
788 23.543795386206178
789 23.54351337351069
790 23.543232657730044
791 23.54295323136945
792 23.542675086984577
793 2

(array([-0.89837364,  0.63896175, -0.17749145,  0.80012826, -2.05573176,
         2.40331676,  0.09870175, -2.86879506,  2.06930356, -1.19923006,
        -2.2211774 ,  0.5821887 , -4.25665526, 22.67578189]),
 23.50442366738613)

### Gradient Descent for num.iterations = 300 and learning_rate = 0.001

In [11]:
gradient_descent(data_train,0.001,300)

1 595.5722716498092
2 591.8404411770802
3 588.1591263708128
4 584.5272505989604
5 580.9437631213744
6 577.407638452818
7 573.917875741715
8 570.4734981642412
9 567.073552333379
10 563.7171077225784
11 560.4032561036386
12 557.1311109984807
13 553.8998071444631
14 550.7084999728925
15 547.556365100426
16 544.4425978330213
17 541.3664126821453
18 538.3270428929271
19 535.3237399839649
20 532.3557732984925
21 529.4224295666344
22 526.5230124784663
23 523.6568422676181
24 520.82325530516
25 518.0216037035152
26 515.2512549301495
27 512.5115914308037
28 509.8020102620232
29 507.1219227327634
30 504.47075405484
31 501.84794300201
32 499.2529415774695
33 496.6852146895594
34 494.1442398354714
35 491.6295067927694
36 489.1405173185184
37 486.6767848558429
38 484.2378342477272
39 481.82320145787827
40 479.43243329848025
41 477.0650871646614
42 474.72073077552415
43 472.39894192155543
44 470.09930821827663
45 467.8214268659687
46 465.56490441532867
47 463.3293565389041
48 461.1144078081738
49 45

(array([-0.25141841,  1.27162725, -0.0553065 ,  1.39118757,  0.0763718 ,
         3.18675002,  0.41290543,  1.02480565,  0.20635646, -0.16204121,
        -0.58710975,  1.46706499, -1.33347343, 10.69739046]),
 177.34391091175897)

### Gradient Descent for num.iterations = 500 and learning_rate = 0.001

In [12]:
gradient_descent(data_train,0.001,500)

1 595.5722716498092
2 591.8404411770802
3 588.1591263708128
4 584.5272505989604
5 580.9437631213744
6 577.407638452818
7 573.917875741715
8 570.4734981642412
9 567.073552333379
10 563.7171077225784
11 560.4032561036386
12 557.1311109984807
13 553.8998071444631
14 550.7084999728925
15 547.556365100426
16 544.4425978330213
17 541.3664126821453
18 538.3270428929271
19 535.3237399839649
20 532.3557732984925
21 529.4224295666344
22 526.5230124784663
23 523.6568422676181
24 520.82325530516
25 518.0216037035152
26 515.2512549301495
27 512.5115914308037
28 509.8020102620232
29 507.1219227327634
30 504.47075405484
31 501.84794300201
32 499.2529415774695
33 496.6852146895594
34 494.1442398354714
35 491.6295067927694
36 489.1405173185184
37 486.6767848558429
38 484.2378342477272
39 481.82320145787827
40 479.43243329848025
41 477.0650871646614
42 474.72073077552415
43 472.39894192155543
44 470.09930821827663
45 467.8214268659687
46 465.56490441532867
47 463.3293565389041
48 461.1144078081738
49 45

373 139.6098705308939
374 139.1664621783113
375 138.7248379462449
376 138.2849904322179
377 137.84691226658444
378 137.41059611234365
379 136.97603466495417
380 136.543220652151
381 136.1121468337639
382 135.68280600153915
383 135.25519097896097
384 134.8292946210761
385 134.40510981431996
386 133.9826294763445
387 133.56184655584764
388 133.14275403240435
389 132.72534491629955
390 132.30961224836247
391 131.89554909980276
392 131.48314857204807
393 131.07240379658288
394 130.6633079347897
395 130.25585417779055
396 129.85003574629073
397 129.44584589042367
398 129.04327788959733
399 128.6423250523422
400 128.24298071615996
401 127.84523824737389
402 127.44909104098109
403 127.0545325205048
404 126.66155613784933
405 126.27015537315486
406 125.8803237346545
407 125.49205475853253
408 125.10534200878304
409 124.72017907707031
410 124.33655958259027
411 123.95447717193312
412 123.57392551894652
413 123.19489832460089
414 122.81738931685521
415 122.4413922505235
416 122.0669009071427
417

(array([-0.42567772,  1.02230924, -0.05978836,  1.39569359,  0.02795455,
         3.64167024,  0.47517516,  0.57964035,  0.30014457, -0.22411427,
        -0.93786891,  1.34741725, -1.90905902, 14.59547728]),
 95.40347570962037)

### Gradient Descent for num.iterations = 1000 and learning_rate = 0.001

In [13]:
gradient_descent(data_train,0.001,1000)

1 595.5722716498092
2 591.8404411770802
3 588.1591263708128
4 584.5272505989604
5 580.9437631213744
6 577.407638452818
7 573.917875741715
8 570.4734981642412
9 567.073552333379
10 563.7171077225784
11 560.4032561036386
12 557.1311109984807
13 553.8998071444631
14 550.7084999728925
15 547.556365100426
16 544.4425978330213
17 541.3664126821453
18 538.3270428929271
19 535.3237399839649
20 532.3557732984925
21 529.4224295666344
22 526.5230124784663
23 523.6568422676181
24 520.82325530516
25 518.0216037035152
26 515.2512549301495
27 512.5115914308037
28 509.8020102620232
29 507.1219227327634
30 504.47075405484
31 501.84794300201
32 499.2529415774695
33 496.6852146895594
34 494.1442398354714
35 491.6295067927694
36 489.1405173185184
37 486.6767848558429
38 484.2378342477272
39 481.82320145787827
40 479.43243329848025
41 477.0650871646614
42 474.72073077552415
43 472.39894192155543
44 470.09930821827663
45 467.8214268659687
46 465.56490441532867
47 463.3293565389041
48 461.1144078081738
49 45

372 140.05507043949117
373 139.6098705308939
374 139.1664621783113
375 138.7248379462449
376 138.2849904322179
377 137.84691226658444
378 137.41059611234365
379 136.97603466495417
380 136.543220652151
381 136.1121468337639
382 135.68280600153915
383 135.25519097896097
384 134.8292946210761
385 134.40510981431996
386 133.9826294763445
387 133.56184655584764
388 133.14275403240435
389 132.72534491629955
390 132.30961224836247
391 131.89554909980276
392 131.48314857204807
393 131.07240379658288
394 130.6633079347897
395 130.25585417779055
396 129.85003574629073
397 129.44584589042367
398 129.04327788959733
399 128.6423250523422
400 128.24298071615996
401 127.84523824737389
402 127.44909104098109
403 127.0545325205048
404 126.66155613784933
405 126.27015537315486
406 125.8803237346545
407 125.49205475853253
408 125.10534200878304
409 124.72017907707031
410 124.33655958259027
411 123.95447717193312
412 123.57392551894652
413 123.19489832460089
414 122.81738931685521
415 122.4413922505235
41

749 53.027742670364695
750 52.927267976642966
751 52.82717994579936
752 52.72747703124775
753 52.62815769270212
754 52.52922039615057
755 52.43066361382924
756 52.332485824196596
757 52.2346855119076
758 52.13726116778845
759 52.04021128881053
760 51.94353437806562
761 51.84722894474
762 51.75129350409006
763 51.655726577416345
764 51.56052669203931
765 51.465692381273925
766 51.371222184405624
767 51.27711464666471
768 51.18336831920248
769 51.08998175906674
770 50.996953529177084
771 50.904282198301225
772 50.81196634103024
773 50.720004537755024
774 50.62839537464189
775 50.53713744360937
776 50.44622934230384
777 50.355669674076196
778 50.26545704795833
779 50.17559007863959
780 50.086067386443524
781 49.99688759730458
782 49.90804934274503
783 49.819551259851714
784 49.731391991253396
785 49.64357018509773
786 49.556084495028465
787 49.46893358016286
788 49.38211610506918
789 49.29563073974391
790 49.20947615958996
791 49.12365104539372
792 49.03815408330321
793 48.95298396480605


(array([-0.62154301,  0.59816882, -0.07370531,  1.18243756, -0.20629037,
         3.85864875,  0.43905807, -0.21424513,  0.50813937, -0.32867807,
        -1.38393967,  1.08252752, -2.7467948 , 19.61189335]),
 36.7531896781517)

### Gradient Descent for num.iterations = 300 and learning_rate = 0.0001

In [14]:
gradient_descent(data_train,0.0001,300)

1 598.9762020098
2 598.5972042807016
3 598.2187266573526
4 597.8407680210464
5 597.4633272557842
6 597.0864032482673
7 596.7099948878953
8 596.3341010667524
9 595.9587206796034
10 595.5838526238897
11 595.2094957997202
12 594.8356491098635
13 594.4623114597438
14 594.0894817574346
15 593.7171589136474
16 593.3453418417342
17 592.9740294576696
18 592.6032206800552
19 592.2329144301043
20 591.8631096316416
21 591.4938052110925
22 591.1250000974817
23 590.7566932224205
24 590.3888835201045
25 590.0215699273044
26 589.6547513833665
27 589.288426830196
28 588.9225952122587
29 588.5572554765712
30 588.1924065726955
31 587.828047452732
32 587.4641770713145
33 587.100794385602
34 586.737898355275
35 586.3754879425265
36 586.0135621120588
37 585.6521198310735
38 585.2911600692689
39 584.9306817988337
40 584.5706839944352
41 584.2111656332225
42 583.8521256948129
43 583.4935631612874
44 583.1354770171873
45 582.7778662495053
46 582.4207298476804
47 582.0640668035924
48 581.7078761115548
49 581.3

(array([0.67670456, 1.19939875, 0.64666463, 1.06963828, 0.68318717,
        1.42334285, 0.74622024, 1.21106656, 0.69602783, 0.63820395,
        0.66187604, 1.19700894, 0.50723343, 2.2436083 ]),
 504.66196214394677)

### Gradient Descent for num.iterations = 500 and learning_rate = 0.0001

In [15]:
gradient_descent(data_train,0.0001,500)

1 598.9762020098
2 598.5972042807016
3 598.2187266573526
4 597.8407680210464
5 597.4633272557842
6 597.0864032482673
7 596.7099948878953
8 596.3341010667524
9 595.9587206796034
10 595.5838526238897
11 595.2094957997202
12 594.8356491098635
13 594.4623114597438
14 594.0894817574346
15 593.7171589136474
16 593.3453418417342
17 592.9740294576696
18 592.6032206800552
19 592.2329144301043
20 591.8631096316416
21 591.4938052110925
22 591.1250000974817
23 590.7566932224205
24 590.3888835201045
25 590.0215699273044
26 589.6547513833665
27 589.288426830196
28 588.9225952122587
29 588.5572554765712
30 588.1924065726955
31 587.828047452732
32 587.4641770713145
33 587.100794385602
34 586.737898355275
35 586.3754879425265
36 586.0135621120588
37 585.6521198310735
38 585.2911600692689
39 584.9306817988337
40 584.5706839944352
41 584.2111656332225
42 583.8521256948129
43 583.4935631612874
44 583.1354770171873
45 582.7778662495053
46 582.4207298476804
47 582.0640668035924
48 581.7078761115548
49 581.3

378 484.9311322352776
379 484.6882531634101
380 484.44561657991494
381 484.20322203071214
382 483.96106906278857
383 483.7191572241928
384 483.4774860640385
385 483.2360551324943
386 482.9948639807866
387 482.75391216119476
388 482.5131992270494
389 482.2727247327285
390 482.03248823365607
391 481.7924892862988
392 481.55272744816483
393 481.3132022778
394 481.07391333478427
395 480.83486017973144
396 480.5960423742859
397 480.3574594811194
398 480.119111063928
399 479.8809966874325
400 479.64311591737146
401 479.4054683205027
402 479.1680534645992
403 478.93087091844586
404 478.6939202518385
405 478.45720103557966
406 478.2207128414787
407 477.9844552423456
408 477.74842781199226
409 477.51263012522793
410 477.27706175785676
411 477.0417222866771
412 476.8066112894757
413 476.5717283450292
414 476.33707303309853
415 476.1026449344291
416 475.86844363074584
417 475.6344687047536
418 475.4007197401316
419 475.1671963215329
420 474.9338980345813
421 474.7008244658716
422 474.467975202962

(array([0.51156899, 1.28586079, 0.47664784, 1.11205626, 0.53281465,
        1.66018313, 0.63067901, 1.29408079, 0.55299   , 0.46156761,
        0.47969575, 1.28890251, 0.24240347, 3.03412062]),
 456.9644777417122)

### Gradient Descent for num.iterations = 1000 and learning_rate = 0.0001

In [16]:
gradient_descent(data_train,0.0001,1000)

1 598.9762020098
2 598.5972042807016
3 598.2187266573526
4 597.8407680210464
5 597.4633272557842
6 597.0864032482673
7 596.7099948878953
8 596.3341010667524
9 595.9587206796034
10 595.5838526238897
11 595.2094957997202
12 594.8356491098635
13 594.4623114597438
14 594.0894817574346
15 593.7171589136474
16 593.3453418417342
17 592.9740294576696
18 592.6032206800552
19 592.2329144301043
20 591.8631096316416
21 591.4938052110925
22 591.1250000974817
23 590.7566932224205
24 590.3888835201045
25 590.0215699273044
26 589.6547513833665
27 589.288426830196
28 588.9225952122587
29 588.5572554765712
30 588.1924065726955
31 587.828047452732
32 587.4641770713145
33 587.100794385602
34 586.737898355275
35 586.3754879425265
36 586.0135621120588
37 585.6521198310735
38 585.2911600692689
39 584.9306817988337
40 584.5706839944352
41 584.2111656332225
42 583.8521256948129
43 583.4935631612874
44 583.1354770171873
45 582.7778662495053
46 582.4207298476804
47 582.0640668035924
48 581.7078761115548
49 581.3

385 483.2360551324943
386 482.9948639807866
387 482.75391216119476
388 482.5131992270494
389 482.2727247327285
390 482.03248823365607
391 481.7924892862988
392 481.55272744816483
393 481.3132022778
394 481.07391333478427
395 480.83486017973144
396 480.5960423742859
397 480.3574594811194
398 480.119111063928
399 479.8809966874325
400 479.64311591737146
401 479.4054683205027
402 479.1680534645992
403 478.93087091844586
404 478.6939202518385
405 478.45720103557966
406 478.2207128414787
407 477.9844552423456
408 477.74842781199226
409 477.51263012522793
410 477.27706175785676
411 477.0417222866771
412 476.8066112894757
413 476.5717283450292
414 476.33707303309853
415 476.1026449344291
416 475.86844363074584
417 475.6344687047536
418 475.4007197401316
419 475.1671963215329
420 474.9338980345813
421 474.7008244658716
422 474.4679752029622
423 474.23534983437696
424 474.0029479496018
425 473.7707691390811
426 473.5388129942153
427 473.3070791073612
428 473.07556707182704
429 472.8442764818701

763 405.86802477245544
764 405.69302221992183
765 405.51814631010615
766 405.3433968547582
767 405.16877366604336
768 404.9942765565393
769 404.8199053392377
770 404.64565982754306
771 404.47153983526954
772 404.29754517664196
773 404.1236756662945
774 403.94993111926823
775 403.7763113510124
776 403.60281617738076
777 403.42944541463527
778 403.25619887943816
779 403.0830763888574
780 402.91007776036093
781 402.7372028118201
782 402.5644513615046
783 402.391823228085
784 402.2193182306279
785 402.04693618859847
786 401.8746769218588
787 401.7025402506654
788 401.53052599566803
789 401.35863397791206
790 401.1868640188349
791 401.0152159402627
792 400.8436895644172
793 400.6722847139044
794 400.5010012117221
795 400.3298388812551
796 400.15879754627525
797 399.98787703093933
798 399.81707715979013
799 399.6463977577531
800 399.4758386501376
801 399.3053996626349
802 399.13508062131694
803 398.96488135263724
804 398.79480168342764
805 398.62484144089774
806 398.455000452635
807 398.2852

(array([ 0.21796961,  1.39528042,  0.20356288,  1.20364014,  0.29610334,
         2.1365337 ,  0.46370346,  1.37086575,  0.33336867,  0.17013744,
         0.1296127 ,  1.42673441, -0.26616271,  4.88167989]),
 367.56940939359515)

In [19]:
#by doing different combination we find that below no.of iterations and learning rate gives the minimum cost

final_slopes=gradient_descent(data_train,0.1,1000)
final_slopes #it prints slope and cost

(array([-9.38080619e-01,  7.41034024e-01,  1.16903739e-02,  7.80873853e-01,
        -2.17455733e+00,  2.35429667e+00,  1.23337963e-01, -2.95232363e+00,
         2.53296564e+00, -1.70290073e+00, -2.25151952e+00,  5.88354235e-01,
        -4.26368148e+00,  2.26772333e+01]),
 23.46605074723138)

In [20]:
final_slopes[0] #it gives only slopes

array([-9.38080619e-01,  7.41034024e-01,  1.16903739e-02,  7.80873853e-01,
       -2.17455733e+00,  2.35429667e+00,  1.23337963e-01, -2.95232363e+00,
        2.53296564e+00, -1.70290073e+00, -2.25151952e+00,  5.88354235e-01,
       -4.26368148e+00,  2.26772333e+01])

In [21]:
col = np.ones((len(data_test),1))
data_test =np.append(data_test,col,axis =1 )#adding coloumn for the intercept
data_test.shape

(127, 14)

In [22]:
y_test = (data_test*final_slopes[0]).sum(axis=1)

In [23]:
y_test

array([12.43328318, 29.03367213, 22.3716447 , 24.4777857 , 20.60167136,
        2.72533224, 30.4000026 , 24.86120001, 18.65725019, 23.53985837,
       24.11396868, 17.71143893, 17.44000487, 21.65356357, 42.31137751,
       23.84974572, 24.47573229, 27.53872766, 20.23606767, 31.15155561,
       23.78238074, 25.00979408, 33.95768519, 36.43515609, 32.04098395,
       16.71322563, 23.47176647, 32.9382817 , 25.18069973, 33.71008693,
       16.88580246, 26.02760937, 23.27040053, 25.47758949, 15.00946626,
       29.58574989, 26.24821246, 20.37245797, 24.43681396,  9.44706904,
        8.38096599, 29.01392307, 29.59085452, 19.75757022, 20.37196752,
        3.14442594, 39.52420107, 25.71741224, 30.37729452, 16.7945324 ,
       17.89088616, 41.02574356, 17.57238763, 20.896627  , 15.59837732,
       21.41394833, 18.45436447, 23.155764  , 13.67245061, 17.23573845,
       15.02710401, 29.15131354, 25.17166505, 25.49749372, 17.21186637,
       17.42936976, 34.70372745, 17.01340775, 27.10724194, 22.54

### Now try to do with the future scaling and inbuilt gradient function from sklearn

In [38]:
import numpy as np
import pandas as pd
import sklearn
from sklearn import preprocessing
from sklearn.ensemble import GradientBoostingRegressor

In [39]:
#load data
data_train=np.genfromtxt('training_boston_x_y_train.csv',delimiter=',')
data_test=np.genfromtxt('test_boston_x_test.csv',delimiter=',')

print(data_train.shape)

(379, 14)


In [40]:
#separate x_train and y_train from given train data
x_train=data_train[:,:-1]
y_train=data_train[:,-1]

print(x_train.shape)
print(y_train.shape)

(379, 13)
(379,)


In [41]:
#scaling
# scaler=preprocessing.StandardScaler()
# scaler.fit(x_train)
# x_train=scaler.transform(x_train)   without future scaling gives better results

In [43]:
model=GradientBoostingRegressor()
model.fit(x_train,y_train)

GradientBoostingRegressor()

In [44]:
y_pred=model.predict(data_test)
y_pred

array([11.9625349 , 26.44625493, 16.71244967, 21.83639359, 19.61490023,
       12.2832724 , 25.28111226, 24.54100496, 18.30477105, 21.93678687,
       23.39058111, 17.85214424, 19.15910094, 20.44435377, 50.98393082,
       22.8620784 , 23.49131107, 22.78191511, 18.97201765, 30.70214326,
       20.58877382, 20.43297718, 37.75828142, 30.69782594, 33.91177519,
       16.48221088, 20.15017985, 30.79439146, 18.45965881, 28.63077438,
       16.89225756, 23.951263  , 19.58209888, 22.62481505,  9.24904647,
       22.62356665, 22.48578852, 20.44057093, 22.62070988,  8.33425299,
       18.95306776, 23.12280455, 25.56204853, 19.50129649, 21.80376912,
        9.75039457, 39.25449469, 24.57774682, 33.20230593, 12.21465241,
       13.59120366, 46.48250046, 14.38762866, 20.74105402, 16.31485807,
       18.52325904, 18.88744499, 22.38409088, 15.32494152, 15.2295322 ,
       13.68437009, 27.27249687, 20.61926732, 23.0038954 , 14.49435547,
       16.30190068, 32.64752054, 12.13576441, 19.93928279, 21.48

In [45]:
#create csv file for the predictions
np.savetxt('predictions1.csv',y_pred,fmt='%.5f',delimiter=',')